# Set new leader/prefix key.
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display "TMUX config reloaded!"

# Better terminal color integration.
set -g default-terminal "tmux-256color"

# Use system clipboard.
set -g set-clipboard on 

# Window/Pane renumbering (start from 1 instead of 0).
set  -g renumber-windows on
set  -g base-index 1
setw -g pane-base-index 1

# Pane splitting. 
bind "|" split-window   -h      -c "#{pane_current_path}"
bind "\\" split-window  -fh     -c "#{pane_current_path}"
bind "-" split-window   -h      -c "#{pane_current_path}"
bind "_" split-window   -fh     -c "#{pane_current_path}"

# Pane navigation.
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Status line.
set -g status-position top
set -g status-justify left
set -g status-style fg=white,bg=black
set -g status-right '#S'
set -g status-right "[%Y-%m-%d %H:%M]"

