# Set new leader/prefix
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

set -g default-terminal "tmux-256color"

set -g renumber-windows on      # Renumber all windows when any window is closed.
set -g base-index 1
setw -g pane-base-index 1

# Pane Splitting
bind    "|"     split-window -h   -c "#{pane_current_path}"
bind    "\\"    split-window -fh  -c "${pane_current_path}" 
bind    "-"     split-window -v   -c "#{pane_current_path}"
bind    "_"     split-window -fv  -c "${pane_current_path}" 
bind    r       source-file ~/tmux.conf \; display "Tmux config reloaded!"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g status-style fg=white,bg=black
set -g status-left '#S'
set -g status-right "%Y-%m-d %H:%M"

set -g set-clipboard on         # Use system clipboard.
set -g status-position top      # Set status line on top

